source 'https://rubygems.org'

# Core dependencies
gem 'easy_translate', '~> 0.5.1'
gem 'nokogiri', '>= 1.19'
gem 'rouge', '~> 4.7'
gem 'prawn', '~> 2.5'
gem 'prawn-table', '~> 0.2.2'
gem 'matrix', '~> 0.4'
gem 'epub-parser', '~> 0.5'
gem 'sqlite3', '~> 2.9'
gem 'fast_blank', '~> 1.0.0'
gem 'concurrent-ruby', '~> 1.3'
gem 'sinatra', '~> 4.2'

gem 'docx', '~> 0.10'

# (Former Tk GUI removed; Sinatra web UI now used cross-platform)

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'rspec-mocks', '~> 3.13'
  gem 'factory_bot', '~> 6.5'
  gem 'observer', '~> 0.1'
  gem 'rack-test', '~> 2.2'
  gem 'rubocop', '~> 1.84'
  gem 'rubocop-rspec', '~> 3.9'
end

group :development do
  gem 'pry', '~> 0.16'
  gem 'pry-byebug', '~> 3.12'
end

ruby '~> 3.4.0'
gem "rackup", "~> 2.3"
gem "puma", "~> 7.2"
