name: translation_fiesta_flutter
description: A Flutter port of FSharpTranslationFiesta - Clean Code TranslationFiesta
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  equatable: ^2.0.5
  either_dart: ^1.0.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
